theme: minima
title: Wonderful World of Ben
description: Dumping ground for several projects
author:
  name: Benjamin Riehl
  email: ghp@riehl.me
minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: benjaminriehl
plugins:
 - jekyll-feed
 - jekyll-seo-tag
