title: Wonderful World of Ben
author:
  name: Benjamin Riehl
  email: ghp@riehl.me
description: >
  Dumping ground for several projects

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: benjaminriehl


header_pages:
  - README.md
  - school/README.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
theme: minima
  skin: dark
