theme: jekyll-theme-minimal
title: Ben's Stuff
description: What do I put here?
url: riehl.me
avatar: https://avatars3.githubusercontent.com/u/3443859
social:
  name: Benjamin Riehl
  links:
    - https://github.com/benjaminriehl